### ISSUE TITLE
I Don't Even Have an Issue with This, But....

### ISSUE THREAD

**Issue by captainbob32** [Florin9doi/WiiBanners#8]
What Even is This? It Said "Wii Banners", But It Doesn't Even Include .BNRs or .WADs. is the Banners in This Repository "Save Data" Banners? I Mean, I Don't Even Know, Since I'm Confused

**Comment by Florin9doi** [comment]
Yeah, savegames

**Comment by captainbob32** [comment]
savegames as in: save datas?

**Comment by captainbob32** [comment]
ok

makes sense
